name: Build iCal
on:
  push: { branches: [ main ] }
  workflow_dispatch:
jobs:
  ics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }
      - run: python scripts/generate_ics.py
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add events.ics
          git commit -m "auto: update events.ics" || echo "no changes"
          git push
