name: Lighthouse CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Lighthouse
        run: npm install -g lighthouse
      - name: Run Lighthouse on Pages
        run: |
          set -e
          mkdir -p reports/lh
          TS=$(date -u +%Y%m%d-%H%M)   # UTC Zeitstempel
          URLS=(
            "https://smartlivingberlin.github.io/smartassist-clean/index.html"
            "https://smartlivingberlin.github.io/smartassist-clean/katalog.html"
            "https://smartlivingberlin.github.io/smartassist-clean/news.html"
            "https://smartlivingberlin.github.io/smartassist-clean/partner.html"
          )
          for U in "${URLS[@]}"; do
            NAME=$(basename "$U" .html)
            echo "🔎 Audit: $U"
            lighthouse "$U" --quiet --chrome-flags="--headless" \
              --output html --output-path "reports/lh/${NAME}-${TS}.report.html"
            # Bequemer "latest"-Alias überschreiben
            cp -f "reports/lh/${NAME}-${TS}.report.html" "reports/lh/${NAME}.latest.report.html"
          done
      - name: Commit Reports
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add reports/lh || true
          git commit -m "auto: Lighthouse reports with timestamp" || echo "no changes"
          git push || true
