name: Build RSS
on:
  push: { branches: [ main ] }
  workflow_dispatch:
  schedule:
    - cron: "15 7 * * *"
jobs:
  rss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }
      - run: python scripts/generate_rss.py
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add news.xml
          git commit -m "auto: update RSS" || echo "no changes"
          git push
